Repository pkgxdev/pantry, pull requests merged in 2024-01, with the labels that each got.

#5002 +github.com/adnanh/webhook
  projects/github.com/adnanh/webhook/package.yml
Labels: request, size:S

#5001 +github.com/skx/marionette
  projects/github.com/skx/marionette/package.yml
Labels: request, size:M

#5005 +github.com/caddyserver/xcaddy
  projects/github.com/caddyserver/xcaddy/package.yml
Labels: size:M

#5004 fix(xz)
  projects/tukaani.org/xz/package.yml
Labels: request, size:XS

#5014 fix(imath)
  projects/openexr.com/imath/package.yml
Labels: size:XS

#5015 fix(mc)
  projects/midnight-commander.org/package.yml
Labels: size:XS

#5023 +nixpacks.com
  projects/nixpacks.com/package.yml
Labels: request, size:S

#5024 +fury.co
  projects/fury.co/package.yml
Labels: request, size:M

#5025 +railway.app
  projects/railway.app/package.yml
Labels: request, size:S

#5026 +github.com/astanin/python-tabulate
  projects/github.com/astanin/python-tabulate/package.yml
Labels: request, size:M

#5027 +gnu.org/parallel
  projects/gnu.org/parallel/package.yml
Labels: request, size:M

#5028 +github.com/tox-dev/filelock
  projects/github.com/tox-dev/filelock/package.yml
Labels: request, size:S

#5029 +btop
  projects/github.com/aristocratos/btop/package.yml
Labels: request, size:M

#5039 fix(fbthrift)
  projects/facebook.com/fbthrift/package.yml
Labels: size:XS

#5031 +github.com/platformdirs/platformdirs
  projects/github.com/platformdirs/platformdirs/package.yml
Labels: request, size:S

#5043 fix(openldap)
  projects/openldap.org/package.yml
Labels: size:XS

#5053 +github.com/libkml/libkml
  projects/github.com/libkml/libkml/package.yml
  projects/github.com/libkml/libkml/test.cpp
Labels: request, size:M

#5050 +github.com/justwatchcom/sql_exporter
  projects/github.com/justwatchcom/sql_exporter/package.yml
Labels: request, size:M

#5055 fix(mergefs)
  projects/spawn.link/package.yml
Labels: size:S

#5059 fix(po4a)
  projects/po4a.org/package.yml
Labels: size:M

#5018 Don’t `--sync` for git aliases
  projects/git-scm.org/git-shim
Labels: request, size:XS

#5060 Add tf-import-gen command
  projects/github.com/kishaningithub/tf-import-gen/package.yml
Labels: request, size:S

#5066 fix(curl)
  projects/curl.se/package.yml
Labels: request, size:S

#5069 fix(grype)
  projects/github.com/anchore/grype/package.yml
Labels: size:S

#5071 +sketchybar+yabai
  projects/felixkratz.github.io/SketchyBar/package.yml
  projects/github.com/koekeishiya/yabai/package.yml
Labels: size:M

#5075 fix(materialize)
  projects/materialize.com/package.yml
Labels: size:XS
