Repository pkgxdev/pantry, pull requests merged in 2024-02, with the labels that each got.

#5077 fix(libusb)
  projects/libusb.info/package.yml
Labels: size:S

#5073 fix(conda)
  projects/conda.org/package.yml
Labels: request, size:M

#5086 fix(openstack)
  projects/opendev.org/openstack/python-openstackclient/package.yml
Labels: request, size:S

#5085 fix(hcloud)
  projects/hetzner.com/hcloud/package.yml
Labels: size:S

#5079 +coder.com
  projects/coder.com/package.yml
Labels: request, size:M

#5088 fix(conda)
  projects/conda.org/package.yml
Labels: size:S

#5087 fix(pulumi)
  .github/workflows/ci.yml
  projects/pulumi.io/package.yml
Labels: size:M

#5093 fix(yarn)
  projects/yarnpkg.com/package.yml
Labels: request, size:XS

#5094 fix(git)
  projects/git-scm.org/package.yml
Labels: size:XS

#5097 fix(yarn)
  projects/yarnpkg.com/package.yml
Labels: size:XS

#5081 ci/plan is less wasteful and more legible
  .github/scripts/get-ci-matrix.ts
  .github/workflows/ci.yml
Labels: request, size:L

#5100 +wordl-rs
  .github/workflows/ci.yml
  projects/crates.io/wordl/add-version.patch
  projects/crates.io/wordl/package.yml
Labels: request, size:M

#5101 fix(kind)
  projects/kind.sigs.k8s.io/package.yml
Labels: size:S

#5103 upload file listing
  .github/workflows/pkg-platform.yml
Labels: request, size:M

#5108 +coder.com/code-server
  projects/coder.com/code-server/package.yml
Labels: request, size:M

#5110 +libusb.info/compat
  projects/libusb.info/compat/package.yml
  projects/libusb.info/compat/test.c
Labels: request, size:M

#5109 +github.com/quodlibet/mutagen
  projects/github.com/quodlibet/mutagen/package.yml
Labels: request, size:S

#5111 +github.com/XCTestHTMLReport/XCTestHTMLReport
  projects/github.com/XCTestHTMLReport/XCTestHTMLReport/package.yml
Labels: request, size:S

#5113 +bitwarden.com
  projects/bitwarden.com/package.yml
Labels: request, size:M

#5114 +github.com/ios-control/ios-deploy
  projects/github.com/ios-control/ios-deploy/package.yml
Labels: request, size:S

#5115 +github.com/Ousret/charset normalizer
  projects/github.com/Ousret/charset_normalizer/package.yml
Labels: request, size:S

#5112 +practical-scheme.net/gauche
  projects/practical-scheme.net/gauche/package.yml
  projects/practical-scheme.net/gauche/test.scm
Labels: request, size:M

#5128 github.com/squidfunk/mkdocs-material add common plugins
  projects/github.com/squidfunk/mkdocs-material/mkdocs.yml
  projects/github.com/squidfunk/mkdocs-material/package.yml
Labels: request, size:S

#5127 +portaudio.com
  projects/portaudio.com/package.yml
  projects/portaudio.com/test.c
Labels: size:M

#5133 fix(ncurses)
  projects/invisible-island.net/ncurses/package.yml
Labels: request, size:S

#5137 github.com/squidfunk/mkdocs-material add missing common plugins
  projects/github.com/squidfunk/mkdocs-material/README.md
  projects/github.com/squidfunk/mkdocs-material/index.md
  projects/github.com/squidfunk/mkdocs-material/mkdocs.yml
  projects/github.com/squidfunk/mkdocs-material/package.yml
Labels: request, size:M

#5146 fix(bitwarden)
  projects/bitwarden.com/package.yml
Labels: size:XS

#5142 fix(mise)
  projects/crates.io/rtx-cli/package.yml
  projects/mise.jdx.dev/package.yml
Labels: size:S

#5147 fix(mvfst)
  projects/facebook.com/mvfst/package.yml
Labels: request, size:XS

#5153 +scriptisto
  projects/github.com/igor-petruk/scriptisto/package.yml
Labels: request, size:M

#5156 fix(cargo)
  projects/rust-lang.org/cargo/package.yml
Labels: request, size:XS

#5125 +dhall-lang.org
  projects/dhall-lang.org/package.yml
Labels: request, size:M

#5148 +github.com/unsignedapps/swift-create-xcframework
  projects/github.com/unsignedapps/swift-create-xcframework/package.yml
Labels: request, size:S

#5157 fix(dhall)
  projects/dhall-lang.org/package.yml
Labels: size:XS

#5160 fix(versio)
  projects/crates.io/versio/package.yml
Labels: request, size:XS

#5158 fix(haskell)
  projects/haskell.org/package.yml
Labels: request, size:XS

#5169 link to libtinfo.so.5
  projects/invisible-island.net/ncurses/package.yml
Labels: size:M

#5166 +github.com/everduin94/better-commits
  projects/github.com/Everduin94/better-commits/package.yml
Labels: request, size:M

#5164 add PIC to haskell
  projects/haskell.org/package.yml
Labels: request, size:S

#5172 Let’s keep our own pantry tarball
  .github/workflows/cd.yml
Labels: request, size:S

#5149 chore(docs): Add details for not using dev
  README.md
Labels: size:XS

#3888 +wails.io
  projects/wails.io/package.yml
Labels: request, size:M

#5181 +wix.com/applesimutils
  projects/wix.com/applesimutils/package.yml
Labels: request, size:M

#5175 +pkl-lang.org
  projects/pkl-lang.org/class.pkl
  projects/pkl-lang.org/package.yml
  projects/pkl-lang.org/template.pkl
Labels: request, size:M

#5183 fix(libproxy)
  projects/libproxy.github.io/libproxy/package.yml
Labels: size:XS

#5182 +github.com/a7ex/xcresultparser
  projects/github.com/a7ex/xcresultparser/package.yml
Labels: request, size:S

#5187 +openpmix.github.io
  projects/openpmix.github.io/package.yml
Labels: request, size:M

#5193 +libimobiledevice.org/libplist
  projects/libimobiledevice.org/libplist/package.yml
Labels: request, size:M

#5207 +github.com/jaraco/keyring
  projects/github.com/jaraco/keyring/package.yml
Labels: size:S, lgtm

#5219 +xdg-user-dirs
  projects/freedesktop.org/xdg-user-dirs/package.yml
Labels: request, size:S

#5220 have pkg-config poll something that exists
  projects/freedesktop.org/pkg-config/package.yml
Labels: request, size:S

#5199 +github.com/jpsim/SourceKitten
  projects/github.com/jpsim/SourceKitten/package.yml
  projects/github.com/jpsim/SourceKitten/patch.diff
Labels: request, size:M, lgtm

#5192 +mpmath.org
  projects/mpmath.org/package.yml
Labels: request, size:S, lgtm

#5194 +github.com/dateutil/dateutil
  projects/github.com/dateutil/dateutil/package.yml
Labels: request, size:S

#5210 +certifi.io/python-certifi
  projects/certifi.io/python-certifi/package.yml
Labels: request, size:M

#5204 +attrs.org
  projects/attrs.org/package.yml
Labels: request, size:S

#5203 +github.com/cpburnz/python-pathspec
  projects/github.com/cpburnz/python-pathspec/package.yml
Labels: request, size:S

#5202 +github.com/giampaolo/psutil
  projects/github.com/giampaolo/psutil/package.yml
Labels: request, size:S

#5201 +github.com/kjd/idna
  projects/github.com/kjd/idna/package.yml
Labels: request, size:S

#5195 +github.com/pyparsing/pyparsing
  projects/github.com/pyparsing/pyparsing/package.yml
Labels: request, size:S

#5241 +maturin
  projects/maturin.rs/package.yml
Labels: request, size:S

#5230 +anchore.com/syft
  projects/anchore.com/syft/package.yml
Labels: request, size:M

#5242 +astral.rs/uv
  projects/astral.sh/uv/package.yml
Labels: request, size:M

#5247 +libtom.net/math
  .github/workflows/cd.pantry.tgz.yml
  .github/workflows/cd.yml
  projects/libtom.net/math/package.yml
Labels: request, size:M

#5265 Add --enable-shared to configure args (to build dylibs, which is needed for torchaudio)
  projects/ffmpeg.org/package.yml
Labels: request, size:XS

#5257 +rye-up.com
  projects/rye-up.com/package.yml
Labels: request, size:M

#5232 +microcks.io
  projects/microcks.io/package.yml
Labels: request, size:M

#5281 +tlr.dev
  projects/tlr.dev/package.yml
Labels: request, size:M

#5280 +charm.sh/skate
  projects/charm.sh/skate/package.yml
Labels: request, size:M

#5205 +vamp-plugins.org
  projects/vamp-plugins.org/package.yml
Labels: request, size:M

#5284 Remove `darwin`-only restriction on `ollama`
  projects/ollama.ai/package.yml
Labels: request, size:M

#5290 +tig
  projects/jonas.github.io/tig/package.yml
Labels: request, size:S

#5291 fix(linkerd2)
  projects/linkerd.io/linkerd2/package.yml
Labels: request, size:S

#5298 fix(watchman)
  projects/facebook.com/watchman/package.yml
Labels: request, size:XS

#5295 add(llvm, more libs)
  projects/llvm.org/package.yml
Labels: request, size:XS

#5240 new/cyrusimap.org/cyrus-sasl
  projects/cyrusimap.org/cyrus-sasl/fixture.cpp
  projects/cyrusimap.org/cyrus-sasl/package.yml
Labels: size:M

#5310 +snyk.io
  projects/snyk.io/package.yml
Labels: request, size:M, lgtm

#5311 +litecli.com
  projects/litecli.com/package.yml
Labels: request, size:M

#5315 fix(gitui)
  projects/crates.io/gitui/package.yml
Labels: request, size:S

#5317 fix(lighthouse)
  projects/crates.io/lighthouse/package.yml
Labels: request, size:XS

#5318 fix(air)
  projects/github.com/cosmtrek/air/package.yml
Labels: request, size:S

#5313 fix(llvm,libc++)
  projects/llvm.org/package.yml
Labels: request, size:XS

#5322 fix(giflib)
  projects/giflib.sourceforge.io/package.yml
Labels: request, size:S

#5323 bump(arrow,protobuf)
  projects/apache.org/arrow/package.yml
Labels: request, size:XS

#5312 +jsonnet.org
  projects/jsonnet.org/package.yml
Labels: request, size:M

#5211 +rbenv.org/ruby-build
  projects/rbenv.org/ruby-build/package.yml
Labels: request, size:M

#5327 fix(deno)
  projects/deno.land/package.yml
Labels: size:M

#5331 fix(glog)
  projects/google.com/glog/package.yml
Labels: request, size:M

#5330 fix(sway)
  projects/fuellabs.github.io/sway/package.yml
Labels: request, size:M

#5332 fix(cloc)
  projects/github.com/AlDanial/cloc/package.yml
Labels: request, size:S

#5334 fix(highway)
  projects/google.com/highway/package.yml
Labels: request, size:M

#5343 fix(glfw)
  projects/glfw.org/package.yml
Labels: request, size:XS

#5353 +sourceforge.net/e2fsprogs
  projects/sourceforge.net/e2fsprogs/package.yml
Labels: request, size:M

#5344 fix(gpt-engineer)
  projects/github.com/AntonOsika/gpt-engineer/package.yml
Labels: request, size:S

#5340 fix(pandoc)
  projects/pandoc.org/package.yml
Labels: request, size:S

#5356 +github.com/kdave/btrfs-progs
  projects/github.com/kdave/btrfs-progs/package.yml
  projects/github.com/kdave/btrfs-progs/patch.diff
Labels: request, size:M

#5357 +sourceware.org/dm
  projects/sourceware.org/dm/package.yml
Labels: request, size:M

#5352 +werf.io
  projects/werf.io/package.yml
Labels: request, size:M

#5360 Remove rye
  projects/rye-up.com/package.yml
Labels: request, size:M
